# Generated by Django 4.1.4 on 2023-02-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_dicount_offers_discount_offers_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='discount',
            field=models.PositiveIntegerField(max_length=12),
        ),
    ]
